name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -race -covermode=atomic -coverprofile=coverage.txt .
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        TEST_UID: ${{ secrets.TEST_UID }}

    - name: Coveralls
      uses: codecov/codecov-action@v1
